/**
 * PDI Constants
 * Default values and known framework mappings
 */

import type { KnownFramework, PDIConfig } from "./types.js";

// ============================================================================
// File Paths
// ============================================================================

export const CLAUDE_DOCS_DIR = ".claude-docs";
export const CONFIG_FILE = "config.json";
export const FRAMEWORKS_DIR = "frameworks";
export const INTERNAL_DIR = "internal";
export const CLAUDE_MD_FILE = "CLAUDE.md";

export const PDI_BEGIN_MARKER =
  "<!-- pdi:begin - auto-generated by passive-docs-index, do not edit manually -->";
export const PDI_END_MARKER = "<!-- pdi:end -->";

// ============================================================================
// Default Configuration
// ============================================================================

export const DEFAULT_CONFIG: PDIConfig = {
  $schema: "https://pdi.dev/schema/config.json",
  version: "1.0.0",
  project: {
    name: "",
    type: "backend",
  },
  sync: {
    lastSync: null,
    autoSyncOnInstall: true,
  },
  frameworks: {},
  internal: {
    enabled: true,
    categories: [],
    totalFiles: 0,
  },
  mcp: {
    fallbackEnabled: true,
    preferredProvider: "context7",
    providers: {
      context7: {
        resolveLibraryId: "mcp__plugin_context7_context7__resolve-library-id",
        queryDocs: "mcp__plugin_context7_context7__query-docs",
      },
    },
    libraryMappings: {},
    cacheHours: 168, // 1 week
  },
  limits: {
    maxIndexKb: 4,
    maxDocsKb: 80,
    maxFilesPerFramework: 20,
  },
};

// ============================================================================
// Known Frameworks
// ============================================================================

export const KNOWN_FRAMEWORKS: KnownFramework[] = [
  // Backend
  {
    pattern: /^hono$/,
    name: "hono",
    displayName: "Hono",
    libraryId: "/honojs/hono",
    category: "backend",
  },
  {
    pattern: /^@hono\//,
    name: "hono",
    displayName: "Hono",
    libraryId: "/honojs/hono",
    category: "backend",
  },
  {
    pattern: /^express$/,
    name: "express",
    displayName: "Express",
    libraryId: "/expressjs/express",
    category: "backend",
  },
  {
    pattern: /^fastify$/,
    name: "fastify",
    displayName: "Fastify",
    libraryId: "/fastify/fastify",
    category: "backend",
  },
  {
    pattern: /^elysia$/,
    name: "elysia",
    displayName: "Elysia",
    libraryId: "/elysiajs/elysia",
    category: "backend",
  },
  {
    pattern: /^@elysiajs\//,
    name: "elysia",
    displayName: "Elysia",
    libraryId: "/elysiajs/elysia",
    category: "backend",
  },

  // Database
  {
    pattern: /^drizzle-orm$/,
    name: "drizzle",
    displayName: "Drizzle ORM",
    libraryId: "/drizzle-team/drizzle-orm",
    category: "database",
  },
  {
    pattern: /^prisma$/,
    name: "prisma",
    displayName: "Prisma",
    libraryId: "/prisma/prisma",
    category: "database",
  },

  // Auth
  {
    pattern: /^better-auth$/,
    name: "better-auth",
    displayName: "Better Auth",
    libraryId: "/better-auth/better-auth",
    category: "auth",
  },
  {
    pattern: /^lucia$/,
    name: "lucia",
    displayName: "Lucia",
    libraryId: "/lucia-auth/lucia",
    category: "auth",
  },
  {
    pattern: /^next-auth$/,
    name: "next-auth",
    displayName: "NextAuth.js",
    libraryId: "/nextauthjs/next-auth",
    category: "auth",
  },

  // Validation
  {
    pattern: /^zod$/,
    name: "zod",
    displayName: "Zod",
    libraryId: "/colinhacks/zod",
    category: "validation",
  },
  {
    pattern: /^@sinclair\/typebox$/,
    name: "typebox",
    displayName: "TypeBox",
    libraryId: "/sinclairzx81/typebox",
    category: "validation",
  },
  {
    pattern: /^valibot$/,
    name: "valibot",
    displayName: "Valibot",
    libraryId: "/fabian-hiller/valibot",
    category: "validation",
  },

  // Frontend
  {
    pattern: /^react$/,
    name: "react",
    displayName: "React",
    libraryId: "/facebook/react",
    category: "frontend",
  },
  {
    pattern: /^next$/,
    name: "nextjs",
    displayName: "Next.js",
    libraryId: "/vercel/next.js",
    category: "frontend",
  },
  {
    pattern: /^vue$/,
    name: "vue",
    displayName: "Vue",
    libraryId: "/vuejs/vue",
    category: "frontend",
  },
  {
    pattern: /^svelte$/,
    name: "svelte",
    displayName: "Svelte",
    libraryId: "/sveltejs/svelte",
    category: "frontend",
  },
  {
    pattern: /^@tanstack\/react-query$/,
    name: "tanstack-query",
    displayName: "TanStack Query",
    libraryId: "/tanstack/query",
    category: "frontend",
  },
  {
    pattern: /^@tanstack\/react-router$/,
    name: "tanstack-router",
    displayName: "TanStack Router",
    libraryId: "/tanstack/router",
    category: "frontend",
  },

  // UI
  {
    pattern: /^shadcn$/,
    name: "shadcn",
    displayName: "shadcn/ui",
    libraryId: "/shadcn-ui/ui",
    category: "ui",
  },

  // Styling
  {
    pattern: /^tailwindcss$/,
    name: "tailwind",
    displayName: "Tailwind CSS",
    libraryId: "/tailwindlabs/tailwindcss.com",
    category: "styling",
  },

  // Build
  {
    pattern: /^vite$/,
    name: "vite",
    displayName: "Vite",
    libraryId: "/vitejs/vite",
    category: "build",
  },
  {
    pattern: /^esbuild$/,
    name: "esbuild",
    displayName: "esbuild",
    libraryId: "/evanw/esbuild",
    category: "build",
  },

  // Testing
  {
    pattern: /^vitest$/,
    name: "vitest",
    displayName: "Vitest",
    libraryId: "/vitest-dev/vitest",
    category: "testing",
  },
  {
    pattern: /^@playwright\/test$/,
    name: "playwright",
    displayName: "Playwright",
    libraryId: "/microsoft/playwright",
    category: "testing",
  },
];

// ============================================================================
// Project Type Detection
// ============================================================================

export const PROJECT_TYPE_INDICATORS = {
  backend: [
    "hono",
    "express",
    "fastify",
    "koa",
    "drizzle-orm",
    "prisma",
    "elysia",
  ],
  frontend: ["react", "vue", "svelte", "next", "@tanstack/react-query"],
  fullstack: ["next", "nuxt", "sveltekit", "remix"],
  library: [], // Detected by package.json fields
  cli: ["commander", "yargs", "meow", "cac"],
};
